######################################################################################################################
#                                                                                                                    #
#                                                THIS IS AN EXAMPLE!                                                 #
#                                                                                                                    #
#                             YOU MUST NOT STORE CONFIGURATION FILES IN THE REPOSITORY!                              #
#                                                                                                                    #
######################################################################################################################

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: blog_production
  username: deployer
  password: deployer
