######################################################################################################################
#                                                                                                                    #
#                                                THIS IS AN EXAMPLE!                                                 #
#                                                                                                                    #
#                             YOU MUST NOT STORE CONFIGURATION FILES IN THE REPOSITORY!                              #
#                                                                                                                    #
######################################################################################################################

production:
  secret_key_base: aea1e00b71fdc723f46ecafa8d0e4be62cf340e3a506097369c587a8f6b63f60bf437c04567e085a6015a27149a5f90143d9c4a3d9950794d0d1712d4e2c78c2
